<?php
/*
File: news_slider.php
Author: Marquis Massie
Description: External PHP component that creates a Bootstrap enabled Carousel slider that shows the user the most recent posts by the company.
Version: 1.0

Please do not edit this file unless you have spoken to the original author
Author Email: massiemarquis@gmail.com
*/
?>
<!-- News Slider -->
<div id="news_carousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators list-unstyled">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides. Each item points to a page and each image should be the featured image for that page.-->
    <div class="carousel-inner" role="listbox">
        <?php
            //Retrieve an array (size of 18) of most recent posts
            $wpb = new WP_QUERY(array('post_type'=>'post', 'post_status'=>'publish', 'post_per_page'=>18));
            if($wpb->have_posts()) : $count = 0;
                while($wpb->have_posts() and $count < 18) : $wpb->the_post();
            //Split array into three different arrrays
            $news_array = array_chunk($wpb, 6); 
            //Set each item class block with an array of posts ?>
            <div class="item active">
                <ul class="pseudo-news">
                    <?php foreach($news_array[0] as $news){?>
                        <li><a href="<?php echo get_page_link(16); ?>"><span><?php the_post_thumbnail(); ?></span></a></li>
                    <?php } ?>
                </ul>
            </div>
            <div class="item">
                <ul class="pseudo-news">
                    <?php foreach($news_array[1] as $news){?>
                        <li><a href="<?php echo get_page_link(16); ?>"><span><?php the_post_thumbnail(); ?></span></a></li>
                    <?php } ?>
                </ul>
            </div>
            <div class="item">
                <ul class="pseudo-news">
                    <?php foreach($news_array[2] as $news){?>
                        <li><a href="<?php echo get_page_link(16); ?>"><span><?php the_post_thumbnail(); ?></span></a></li>
                    <?php } ?>
                </ul>
            </div>
        <?php endwhile; 
            endif;
        ?> 
    </div>
</div>